<?php
  //CUANDO USAMOS LAS COMILLAS DOBLES PODEMOS USAR LAS VAREBLES SIN TENER QUE CONCATENAR CON .<VARIABLE> PERO TIENEN UN PROCESADO MAS LENTO.
  $miEdad = 24;
  echo "Mi edad es  $miEdad"."<hr>";

  //COMILLAS SIMPLES: SE CONCATENA PERO TIENE UN PROCESADO MAS RAPIDO
  echo 'Mi edad es'.$miEdad;

?>